/**
 * Append-only sessions[] — Architect contract (schemaVersion 1, additive field 2026-10-06):
 *   { id, date, bookId, minutes, pageTurns }
 *   `id` = session UUID generated by the reader (crypto.randomUUID, random fallback) — it is the
 *   IDB key and the idempotency key for game awards (game.awardedSessionIds). Never an
 *   IndexedDB autoincrement number. Pre-2026-10-06 rows get a deterministic
 *   `legacy-<date>-<bookId>-<minutes>-<pageTurns>-<index>` id (see legacySessionId).
 *
 * Stored in IndexedDB store `sessions` (can grow; not localStorage).
 * Reader calls logSession at end of session; game/metrics only read.
 *
 * North-star: days/week with ≥10 minutes → daysMeetingThreshold({ minMinutes: 10 }).
 */
import { IDB_STORE_SESSIONS } from './schema.js?v=20261008-1027';
import { openDb } from './idb.js?v=20261008-1027';

/** Session UUID (reader-generated). crypto.randomUUID with a random v4 fallback. */
export function newSessionId() {
  try {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID();
  } catch (e) { /* insecure context */ }
  const a = new Uint8Array(16);
  try { crypto.getRandomValues(a); } catch (e) { for (let i = 0; i < 16; i++) a[i] = Math.floor(Math.random() * 256); }
  a[6] = (a[6] & 0x0f) | 0x40; a[8] = (a[8] & 0x3f) | 0x80;
  let s = '';
  for (let i = 0; i < 16; i++) {
    s += (a[i] + 0x100).toString(16).slice(1);
    if (i === 3 || i === 5 || i === 7 || i === 9) s += '-';
  }
  return s;
}

/** True for a real session id (string). Numbers = old IDB autoincrement keys. */
export function hasSessionId(row) {
  return !!row && typeof row.id === 'string' && row.id.length > 0;
}

/**
 * Deterministic id for a pre-2026-10-06 row (no UUID). `index` = position among the
 * id-less rows ordered by (date, old numeric key / array position). Same data → same id,
 * so re-importing an old export stays idempotent.
 */
export function legacySessionId(row, index) {
  return 'legacy-' + normalizeDate(row.date) + '-' + String(row.bookId) + '-' +
    String(Number(row.minutes) || 0) + '-' + String(Number(row.pageTurns != null ? row.pageTurns : row.pages) || 0) + '-' + index;
}

/** Assign legacy ids to every id-less row of an array (returns new objects, order kept). */
export function withLegacyIds(rows) {
  const list = (rows || []).map(function (r, i) { return { r: r, i: i }; });
  const legacy = list.filter(function (x) { return x.r && !hasSessionId(x.r); });
  legacy.sort(function (a, b) {
    const da = normalizeDate(a.r.date), db = normalizeDate(b.r.date);
    if (da !== db) return da < db ? -1 : 1;
    const ka = typeof a.r.id === 'number' ? a.r.id : a.i, kb = typeof b.r.id === 'number' ? b.r.id : b.i;
    return ka - kb;
  });
  const ids = new Map();
  legacy.forEach(function (x, idx) { ids.set(x.i, legacySessionId(x.r, idx)); });
  return list.map(function (x) {
    if (!x.r || hasSessionId(x.r)) return x.r;
    return Object.assign({}, x.r, { id: ids.get(x.i) });
  });
}

/**
 * THE day helper (2026-10-06, Product): a reading day is the device's LOCAL calendar day,
 * never the UTC day (toISOString). YYYY-MM-DD from getFullYear/getMonth/getDate.
 * @param {number|Date|string} [ts] timestamp (ms), Date or date-like; default = now (Date.now()).
 */
export function localDay(ts) {
  const x = ts instanceof Date ? ts : new Date(ts == null || ts === '' ? Date.now() : ts);
  const y = x.getFullYear();
  const m = String(x.getMonth() + 1).padStart(2, '0');
  const day = String(x.getDate()).padStart(2, '0');
  return y + '-' + m + '-' + day;
}

/** Local-day key of `ts` shifted by `n` calendar days (DST-safe: setDate, not 86400000 ms). */
export function addLocalDays(day, n) {
  const p = String(day).slice(0, 10).split('-').map(Number);
  return localDay(new Date(p[0], p[1] - 1, p[2] + (n || 0), 12, 0, 0));
}

/** Backward-compatible alias (same local-day semantics). */
export function dayKey(d) { return localDay(d); }

export function normalizeDate(input) {
  if (!input) return localDay(Date.now());
  if (typeof input === 'string') {
    if (/^\d{4}-\d{2}-\d{2}$/.test(input)) return input;
    return dayKey(new Date(input));
  }
  if (input instanceof Date) return dayKey(input);
  return localDay(Date.now());
}

/**
 * Append one reading session (Architect shape).
 * @param {{ id?: string, date?: string|Date, bookId: string, minutes: number, pageTurns: number }} entry
 * @returns {Promise<{id:string, date:string, bookId:string, minutes:number, pageTurns:number}>}
 * Duplicate id → rejects (ConstraintError): a session can never be stored twice.
 */
export async function logSession(entry) {
  if (!entry || typeof entry !== 'object') {
    throw new Error('logSession: entry required');
  }
  if (entry.bookId == null || entry.bookId === '') {
    throw new Error('logSession: bookId required');
  }
  const minutes = Number(entry.minutes);
  if (!Number.isFinite(minutes) || minutes < 0) {
    throw new Error('logSession: minutes must be a non-negative number');
  }
  // Accept legacy alias `pages` once; persist only as pageTurns
  const rawTurns =
    entry.pageTurns != null ? entry.pageTurns : entry.pages != null ? entry.pages : 0;
  const pageTurns = Number(rawTurns);
  if (!Number.isFinite(pageTurns) || pageTurns < 0) {
    throw new Error('logSession: pageTurns must be a non-negative number');
  }

  const rec = {
    id: hasSessionId(entry) ? entry.id : newSessionId(),
    date: normalizeDate(entry.date),
    bookId: String(entry.bookId),
    minutes: minutes,
    pageTurns: pageTurns,
  };

  const db = await openDb();
  return new Promise(function (res, rej) {
    const tx = db.transaction(IDB_STORE_SESSIONS, 'readwrite');
    const store = tx.objectStore(IDB_STORE_SESSIONS);
    store.add(rec);
    tx.oncomplete = function () {
      res(Object.assign({}, rec));
    };
    tx.onerror = function () {
      rej(tx.error);
    };
  });
}

/**
 * List sessions[] (Architect records). Optional inclusive date range / bookId.
 * @param {{ from?: string|Date, to?: string|Date, bookId?: string }} [opts]
 */
export async function listSessions(opts) {
  const options = opts || {};
  const from = options.from != null ? normalizeDate(options.from) : null;
  const to = options.to != null ? normalizeDate(options.to) : null;
  const bookId = options.bookId != null ? String(options.bookId) : null;

  const db = await openDb();
  return new Promise(function (res, rej) {
    const tx = db.transaction(IDB_STORE_SESSIONS, 'readonly');
    const store = tx.objectStore(IDB_STORE_SESSIONS);
    const req = store.getAll();
    req.onsuccess = function () {
      let rows = req.result || [];
      if (from) rows = rows.filter(function (r) { return r.date >= from; });
      if (to) rows = rows.filter(function (r) { return r.date <= to; });
      if (bookId) rows = rows.filter(function (r) { return r.bookId === bookId; });
      rows.sort(function (a, b) {
        if (a.date !== b.date) return a.date < b.date ? -1 : 1;
        return 0; // stable: IDB key order within a day
      });
      res(rows);
    };
    req.onerror = function () {
      rej(req.error);
    };
  });
}

/** Minutes / pageTurns per calendar day (for north-star). */
export async function aggregateSessionsByDay(opts) {
  const rows = await listSessions(opts);
  const map = {};
  for (let i = 0; i < rows.length; i++) {
    const r = rows[i];
    if (!map[r.date]) map[r.date] = { minutes: 0, pageTurns: 0, sessions: 0 };
    map[r.date].minutes += r.minutes || 0;
    map[r.date].pageTurns += r.pageTurns || 0;
    map[r.date].sessions += 1;
  }
  return map;
}

/**
 * North-star: distinct days with total minutes ≥ threshold (default 10 = defaultMinutes).
 */
export async function daysMeetingThreshold(opts) {
  const options = opts || {};
  const min = options.minMinutes != null ? Number(options.minMinutes) : 10;
  const byDay = await aggregateSessionsByDay(options);
  const days = Object.keys(byDay).filter(function (d) {
    return byDay[d].minutes >= min;
  });
  days.sort();
  return { count: days.length, days: days, minMinutes: min, byDay: byDay };
}

/**
 * One-time, idempotent: rows stored before 2026-10-06 have numeric autoincrement keys.
 * Re-key them to their deterministic legacy id (same rule as import).
 */
export async function ensureSessionIds() {
  const db = await openDb();
  return new Promise(function (res, rej) {
    const tx = db.transaction(IDB_STORE_SESSIONS, 'readwrite');
    const store = tx.objectStore(IDB_STORE_SESSIONS);
    const req = store.getAll();
    let changed = 0;
    req.onsuccess = function () {
      const rows = req.result || [];
      if (!rows.some(function (r) { return !hasSessionId(r); })) return;
      const fixed = withLegacyIds(rows);
      rows.forEach(function (r, i) {
        if (hasSessionId(r)) return;
        if (r.id != null) store.delete(r.id);
        store.put(fixed[i]);
        changed++;
      });
    };
    tx.oncomplete = function () { res({ changed: changed }); };
    tx.onerror = function () { rej(tx.error); };
  });
}

export async function clearSessions() {
  const db = await openDb();
  return new Promise(function (res, rej) {
    const tx = db.transaction(IDB_STORE_SESSIONS, 'readwrite');
    tx.objectStore(IDB_STORE_SESSIONS).clear();
    tx.oncomplete = function () {
      res();
    };
    tx.onerror = function () {
      rej(tx.error);
    };
  });
}

